/* ************************************************************************

    custom.Simple

    qooxdoo v.0.7 code generated by QxTransformer v.

************************************************************************ */


/* ************************************************************************
#embed(qx.icontheme/16/actions/encrypt.png)


************************************************************************ */

/**
 * Widget class definition
 */
qx.Class.define("qcl.components.loginWidget.window.Simple",
{
  extend : qx.ui.window.Window,

  include : [ qcl.components.login.window.SimpleHandlers ],

    
  /**
   * widget property, is deprecated and will be removed
   * @deprecated
   */
  properties : {
        widget : { check : "Object" }
  },
    
  /**
   * Constructor
   */
  construct : function(caption, icon)
  {
    // call parent class
    this.base(arguments);

    //call paint method to draw widget
    this.paint();
  },

  members :
  {

    /**
     * Draw widget
     */
    paint: function ()
    {

      // parent object to which child objects will be added: this object or dummy stub, depends on setToClientDocument property
      var qx_id96029= this;

/** begin auto-generated gui code **/

var qx_id99888 = new qx.ui.groupbox.GroupBox(null,null);
qx_id99888.setDimension("auto" ,"auto");
qx_id96029.add(qx_id99888);

var qx_id99891 = new qx.ui.layout.VerticalBoxLayout();
qx_id99891.setSpacing(5);
qx_id99888.add(qx_id99891);

var qx_id99895 = new qx.ui.basic.Atom(this.tr("Please log in."),"icon/16/actions/encrypt.png");
qx_id99895.setHeight(20);
qx_id99895.setWidth("auto");
qx_id99895.setIconPosition("left");
qx_id99891.add(qx_id99895);

var qx_id99907 = new qx.ui.layout.GridLayout();
qx_id99907.setDimension("auto" ,"auto");
qx_id99907.setVerticalSpacing(5);
qx_id99907.setHorizontalSpacing(5);
qx_id99891.add(qx_id99907);
qx_id99907.setRowCount(3);
qx_id99907.setColumnCount(2);
qx_id99907.setColumnWidth(0,70);
qx_id99907.setColumnHorizontalAlignment(0,"right");
qx_id99907.setColumnVerticalAlignment(0,"top");
qx_id99907.setColumnWidth(1,180);
qx_id99907.setColumnHorizontalAlignment(1,"right");
qx_id99907.setColumnVerticalAlignment(1,"top");
qx_id99907.setRowHeight(0,20);

var qx_id99933 = new qx.ui.basic.Label(this.tr("User Name"));
qx_id99907.add(qx_id99933,0,0);

this.usernameField = new qx.ui.form.TextField();
this.usernameField.setWidth("100%");
this.usernameField.setHeight(20);
qx_id99907.add(this.usernameField,1,0);
qx_id99907.setRowHeight(1,20);

var qx_id99950 = new qx.ui.basic.Label(this.tr("Password"));
qx_id99907.add(qx_id99950,0,1);

this.passwordField = new qx.ui.form.PasswordField();
this.passwordField.setWidth("100%");
this.passwordField.setHeight(20);
qx_id99907.add(this.passwordField,1,1);
qx_id99907.setRowHeight(2,20);

var qx_id99969 = new qx.ui.layout.HorizontalBoxLayout();
qx_id99969.setSpacing(5);

var qx_id99972 = new qx.ui.form.Button(this.tr("Login"),null);
qx_id99972.setWidth(100);
qx_id99969.add(qx_id99972);

qx_id99972.addEventListener("execute", function(event){this.onSubmit(event,qx_id99972);},this);
qx_id99907.add(qx_id99969,1,2);

qx.event.message.Bus.subscribe("qcl.auth.messages.loginFailed",function(message){

			var msg = message.getData();
			if (msg) alert(msg);
		
},qx_id96029);

qx.event.message.Bus.subscribe("qcl.auth.messages.loginSuccess",function(message){

			this.close();
		
},qx_id96029);

qx.event.message.Bus.subscribe("qcl.auth.messages.logout",function(message){

			this.show();
		
},qx_id96029);

/** end auto-generated gui code **/

      // set widget object, deprecated, will be removed
      this.setWidget(this);
    }

  }

});


