/* ************************************************************************


    Widget class 'qcl.components.jsonrpc.StatusIndicator'.
    This file is auto-generated. Do not edit, manual changes will be overwritten.


    qooxdoo v.0.7 code generated by QxTransformer v.

************************************************************************ */


/* ************************************************************************
#embed(qx.icontheme/16/actions/ajax-loader.gif)


************************************************************************ */

/**
 * @todo: add documentation here auto-generated from qxml file
 */
qx.Class.define("qcl.components.jsonrpc.StatusIndicator",
{
  extend : qx.ui.popup.Popup,

  include : [ qcl.components.jsonrpc.MStatusIndicator ],

    
  /**
   * widget property, is deprecated and will be removed
   * @deprecated
   */
  properties : {
        widget : { check : "Object" }
  },
    
  /**
   * Constructor
   */
  construct : function()
  {
    // call parent class
    this.base(arguments);

    //call paint method to draw widget
    this.paint();
  },


  members :
  {

    /**
     * Draw widget
     */
    paint: function ()
    {
      // Client document object
      var qx_id97014 = qx.ui.core.ClientDocument.getInstance();

/** begin auto-generated gui code **/

this.setHeight("auto");
this.setWidth("auto");
this.setBorder("black");
this.setAutoHide(false);

this.addEventListener("appear",function(event)
{
this.centerToBrowser()
},this);

var qx_id98179 = new qx.ui.basic.Atom(this.tr("Busy ..."),"icon/16/actions/ajax-loader.gif");
qx_id98179.setPadding(10);
qx_id98179.setBackgroundColor("white");
this.add(qx_id98179);

qx.event.message.Bus.subscribe("qcl.databinding.messages.rpc.*",function(message){this.handleRpcMessage(message,qx_id98179);},this);

qx_id98179.addEventListener("click", function(event){this.handleClick(event,qx_id98179);},this);

/** end auto-generated gui code **/

      // set widget object, deprecated, will be removed
      this.setWidget(this);
    }

  }

});


