download-0.7:
	wget 'http://belnet.dl.sourceforge.net/sourceforge/qooxdoo/qooxdoo-0.7-sdk.zip'
	unzip qooxdoo-0.7-sdk.zip
	rm -rf qooxdoo-0.7-sdk.zip
	
download-trunk:
	svn co https://qooxdoo.svn.sourceforge.net/svnroot/qooxdoo/trunk/qooxdoo trunk
	svn up trunk
	