/* ************************************************************************


    Widget class 'qcl.components.dialog.Simple'.
    This file is auto-generated. Do not edit, manual changes will be overwritten.


    qooxdoo v.0.7 code generated by QxTransformer v.

************************************************************************ */


/* ************************************************************************


************************************************************************ */

/**
 * @todo: add documentation here auto-generated from qxml file
 */
qx.Class.define("qcl.components.dialog.Error",
{
  extend : qx.ui.window.Window,

    
  /**
   * widget property, is deprecated and will be removed
   * @deprecated
   */
  properties : {
        widget : { check : "Object" }
  },
    
  /**
   * Constructor
   */
  construct : function()
  {
    // call parent class
    this.base(arguments);

    //call paint method to draw widget
    this.paint();
  },


  members :
  {

    /**
     * Draw widget
     */
    paint: function ()
    {
      // Client document object
      var qx_id97124 = qx.ui.core.ClientDocument.getInstance();

/** begin auto-generated gui code **/

this.setWidth(400);
this.setHeight("auto");
this.setCaption(this.tr("Error"));
this.setShowMinimize(false);
this.setShowMaximize(false);
this.setShowClose(false);

this.addEventListener("appear",function(event)
{
this.centerToBrowser()
},this);

var qx_id98213 = new qx.ui.layout.VerticalBoxLayout();
qx_id98213.setSpacing(5);
qx_id98213.setPadding(10);
qx_id98213.setWidth("100%");
qx_id98213.setHeight("100%");
this.add(qx_id98213);

var qx_id98182 = new qx.ui.layout.HorizontalBoxLayout();
qx_id98182.setWidth("100%");
qx_id98182.setHeight("1*");
qx_id98182.setSpacing(10);
qx_id98182.setVerticalChildrenAlign("middle");
qx_id98213.add(qx_id98182);

var qx_id100184 = new qx.ui.basic.Image("icon/32/status/dialog-error.png");
qx_id100184.setDimension(32 ,32);
qx_id98182.add(qx_id100184);

var qx_id100189 = new qx.ui.basic.Label(this.tr(" "));
qx_id100189.setWrap(true);
qx_id100189.setHeight("100%");
qx_id100189.setWidth("1*");
qx_id100189.setMode("html");
qx_id98182.add(qx_id100189);

var qx_id100199 = new qx.ui.layout.HorizontalBoxLayout();
qx_id100199.setWidth("100%");
qx_id100199.setHeight("auto");
qx_id100199.setHorizontalChildrenAlign("center");
qx_id100199.setSpacing(10);
qx_id98213.add(qx_id100199);

var qx_id100208 = new qx.ui.form.Button(this.tr("OK"),null);
qx_id100208.setHeight(25);
qx_id100208.setWidth(70);
qx_id100199.add(qx_id100208);

qx_id100208.addEventListener("execute", function(event){this.closeWindow(event,qx_id100208);},this);

/** end auto-generated gui code **/

      // set widget object, deprecated, will be removed
      this.setWidget(this);
    },

    /**
     * 
     * @param event {qx.event.type.Event}
     * @param target {qx.core.Target}
     */ 
    closeWindow : function(event,target)
    {

      this.close();
    
    }

  }

});


