/* ************************************************************************


    Widget class 'qcl.components.dialog.Error'.
    This file is auto-generated. Do not edit, manual changes will be overwritten.


    qooxdoo v.0.7 code generated by QxTransformer v.

************************************************************************ */


/* ************************************************************************


************************************************************************ */

/**
 * @todo: add documentation here auto-generated from qxml file
 */
qx.Class.define("qcl.components.dialog.Error",
{
  extend : qx.ui.window.Window,

    
  /**
   * widget property, is deprecated and will be removed
   * @deprecated
   */
  properties : {
        widget : { check : "Object" }
  },
    
  /**
   * Constructor
   */
  construct : function()
  {
    // call parent class
    this.base(arguments);

    //call paint method to draw widget
    this.paint();
  },


  members :
  {

    /**
     * Draw widget
     */
    paint: function ()
    {
      // Client document object
      var qx_id97222 = qx.ui.core.ClientDocument.getInstance();

/** begin auto-generated gui code **/

this.setWidth(400);
this.setHeight("auto");
this.setCaption(this.tr("Error"));
this.setShowMinimize(false);
this.setShowMaximize(false);
this.setShowClose(false);

this.addEventListener("appear",function(event)
{
this.centerToBrowser()
},this);

var qx_id98311 = new qx.ui.layout.VerticalBoxLayout();
qx_id98311.setSpacing(5);
qx_id98311.setPadding(10);
qx_id98311.setWidth("100%");
qx_id98311.setHeight("100%");
this.add(qx_id98311);

var qx_id98282 = new qx.ui.layout.HorizontalBoxLayout();
qx_id98282.setWidth("100%");
qx_id98282.setHeight("1*");
qx_id98282.setSpacing(10);
qx_id98282.setVerticalChildrenAlign("middle");
qx_id98311.add(qx_id98282);

var qx_id100281 = new qx.ui.basic.Image("icon/32/status/dialog-error.png");
qx_id100281.setDimension(32 ,32);
qx_id98282.add(qx_id100281);

var qx_id100286 = new qx.ui.basic.Label(this.tr(" "));
qx_id100286.setWrap(true);
qx_id100286.setHeight("100%");
qx_id100286.setWidth("1*");
qx_id100286.setMode("html");
qx_id98282.add(qx_id100286);

var qx_id100296 = new qx.ui.layout.HorizontalBoxLayout();
qx_id100296.setWidth("100%");
qx_id100296.setHeight("auto");
qx_id100296.setHorizontalChildrenAlign("center");
qx_id100296.setSpacing(10);
qx_id98311.add(qx_id100296);

var qx_id100305 = new qx.ui.form.Button(this.tr("OK"),null);
qx_id100305.setHeight(25);
qx_id100305.setWidth(70);
qx_id100296.add(qx_id100305);

qx_id100305.addEventListener("execute", function(event){this.closeWindow(event,qx_id100305);},this);

/** end auto-generated gui code **/

      // set widget object, deprecated, will be removed
      this.setWidget(this);
    },

    /**
     * 
     * @param event {qx.event.type.Event}
     * @param target {qx.core.Target}
     */ 
    closeWindow : function(event,target)
    {

      this.close();
    
    }

  }

});


