/**
    Generated by QxTransformer v.0.4.
    Author Christian Boulanger
**/

/*------------------------------------------------------------------------------

#require(qx.*)
#require(qcl.databinding.event.*)
------------------------------------------------------------------------------*/
qx.Class.define("access.Application",
{
      extend : access.Main,
  
  
  
      members : { 
        main: function() {
            this.base(arguments);
            this.__qxtCreateUI();
        },

        __qxtCreateUI : function() {
            
            var qxVbox1 = new qx.ui.layout.VBox(null, null, null);
    

    var qxComposite1 = new qx.ui.container.Composite();
qxComposite1.setLayout(qxVbox1)



this.getRoot().add(qxComposite1, {edge:0});


            
    

            

    var componentsMainToolBar1 = new access.components.MainToolBar();
    


    
    

    

qxComposite1.add(componentsMainToolBar1 );

    







	


    

        }
        
    }


});






