package com.zenesis.qx.remote.relaxng;

import java.util.HashMap;

import org.dom4j.Element;

import com.zenesis.qx.remote.DynamicTypeProvider;
import com.zenesis.qx.remote.ProxyType;

/**
 * An object generated by the RelaxNG parser
 * 
 * @author john
 */
public class Instance implements DynamicTypeProvider {
	
	// The type definition
	private final RngProxyType proxyType;
	
	// Values
	private final HashMap<String, Object> propertyValues = new HashMap<String, Object>();
	
	/**
	 * Constructor
	 * @param proxyType
	 */
	public Instance(RngProxyType proxyType) {
		super();
		this.proxyType = proxyType;
	}
	
	/* (non-Javadoc)
	 * @see com.zenesis.qx.remote.DynamicTypeProvider#getProxyType()
	 */
	@Override
	public ProxyType getProxyType() {
		return proxyType;
	}

	/**
	 * Writes the object into XML
	 * @return
	 */
	public Element saveAsXml() {
		return proxyType.saveAsXml(this, propertyValues);
	}

	/**
	 * Gets a property value
	 * @param name
	 * @return
	 */
	public Object getValue(String name) {
		return propertyValues.get(name);
	}
	
	/**
	 * Sets a property value
	 * @param name
	 * @param value
	 */
	public void setValue(String name, Object value) {
		propertyValues.put(name, value);
	}
}
