>>> Parsing file...
>>> Creating tree...
>>> Optimizing basecalls...
>>> Optimizing strings...
>>> Optimizing variables...
>>> Optimizing privates...
>>> Compiling...
(function(){var d="theobj",c="ownerObjRef",b="ownersId";
(function({add:function(o){var t=new qx.ui.tree.TreeFolder(o.getLabel());
var f=o.getMenuTree();

for(a in f){var e=new qx.ui.tree.TreeFile(f[a][0]);
e.setUserData(d,undefined);
e.setUserData(b,f[a][1]);
e.setUserData(c,this.__getObjRef(o));
t.add(e);
}}}){})();
})();

