<%namespace name="utils" file="../../utils/utils.mako"/>\
<%inherit file="../qx/widget.mako"/>\

<%def name="new()">\
    //connecting autogenerated id with 'this'
    var ${utils.rawAttrib("id")} = this;
</%def>

<%def name="add()">\
</%def>
