/* ************************************************************************


    Widget class 'qcl.components.login.popup.error.alert.Simple'.
    This file is auto-generated. Do not edit, manual changes will be overwritten.


    qooxdoo v.0.7 code generated by QxTransformer v.

************************************************************************ */


/* ************************************************************************


************************************************************************ */

/**
 * @todo: add documentation here auto-generated from qxml file
 */
qx.Class.define("qcl.components.login.popup.error.alert.Simple",
{
  extend : qx.ui.window.Window,

    
  /**
   * widget property, is deprecated and will be removed
   * @deprecated
   */
  properties : {
        widget : { check : "Object" }
  },
    
  /**
   * Constructor
   */
  construct : function()
  {
    // call parent class
    this.base(arguments);

    //call paint method to draw widget
    this.paint();
  },


  members :
  {

    /**
     * Draw widget
     */
    paint: function ()
    {

      // parent object to which child objects will be added: this object or dummy stub, depends on setToClientDocument property
      var qx_id96738= this;

/** begin auto-generated gui code **/

qx.event.message.Bus.subscribe("qcl.databinding.messages.rpc.error",function(message){

			message.getData() == false ? this.hide() : this.show();
		
},qx_id96738);

var qx_id97917 = new qx.ui.layout.VerticalBoxLayout();
qx_id97917.setSpacing(5);
qx_id97917.setPadding(10);
qx_id97917.setWidth("100%");
qx_id97917.setHeight("100%");
qx_id96738.add(qx_id97917);

var qx_id97923 = new qx.ui.layout.HorizontalBoxLayout();
qx_id97923.setWidth("100%");
qx_id97923.setHeight("1*");
qx_id97923.setSpacing(10);
qx_id97923.setVerticalChildrenAlign("middle");
qx_id97917.add(qx_id97923);

var qx_id99911 = new qx.ui.basic.Image("icon/32/status/dialog-error.png");
qx_id99911.setDimension(32 ,32);
qx_id97923.add(qx_id99911);

var qx_id99917 = new qx.ui.basic.Label(" ");
qx_id99917.setWrap(true);
qx_id99917.setHeight("100%");
qx_id99917.setWidth("1*");
qx_id99917.setMode("html");

qx.event.message.Bus.subscribe("qcl.databinding.messages.rpc.error",function(message){

  					var msg = message.getData() || "";
  					var msg = "" + msg.replace(/\\n/,"") + "";
  					this.setText(msg);
  				
},qx_id99917);
qx_id97923.add(qx_id99917);

var qx_id99940 = new qx.ui.layout.HorizontalBoxLayout();
qx_id99940.setWidth("100%");
qx_id99940.setHeight("auto");
qx_id99940.setHorizontalChildrenAlign("center");
qx_id99940.setSpacing(10);
qx_id97917.add(qx_id99940);

var qx_id99948 = new qx.ui.form.Button("OK",null);
qx_id99948.setHeight(25);
qx_id99948.setWidth(70);
qx_id99940.add(qx_id99948);

qx_id99948.addEventListener("execute",function(event){

						errorWindow.hide();
					
},qx_id99948);

/** end auto-generated gui code **/

      // set widget object, deprecated, will be removed
      this.setWidget(this);
    }

  }

});


