/* ************************************************************************


    Widget class 'qcl.components.popup.error.alert.Simple'.
    This file is auto-generated. Do not edit, manual changes will be overwritten.


    qooxdoo v.0.7 code generated by QxTransformer v.

************************************************************************ */


/* ************************************************************************


************************************************************************ */

/**
 * @todo: add documentation here auto-generated from qxml file
 */
qx.Class.define("qcl.components.popup.error.alert.Simple",
{
  extend : qx.ui.window.Window,

    
  /**
   * widget property, is deprecated and will be removed
   * @deprecated
   */
  properties : {
        widget : { check : "Object" }
  },
    
  /**
   * Constructor
   */
  construct : function()
  {
    // call parent class
    this.base(arguments);

    //call paint method to draw widget
    this.paint();
  },


  members :
  {

    /**
     * Draw widget
     */
    paint: function ()
    {
      // Parent object to which child objects will be added: this object or dummy stub, depends on setToClientDocument property
      var qx_id96931= this;

/** begin auto-generated gui code **/

this.setWidth(400);
this.setHeight("auto");
this.setCaption(this.tr("Error"));
this.setShowMinimize(false);
this.setShowMaximize(false);
this.setShowClose(false);

this.addEventListener("appear",function(event)
{
this.centerToBrowser()
},this);

qx.event.message.Bus.subscribe("qcl.databinding.messages.rpc.error",function(message){

			message.getData() == false ? this.hide() : this.show();
		
},qx_id96931);

var qx_id98069 = new qx.ui.layout.VerticalBoxLayout();
qx_id98069.setSpacing(5);
qx_id98069.setPadding(10);
qx_id98069.setWidth("100%");
qx_id98069.setHeight("100%");
qx_id96931.add(qx_id98069);

var qx_id100059 = new qx.ui.layout.HorizontalBoxLayout();
qx_id100059.setWidth("100%");
qx_id100059.setHeight("1*");
qx_id100059.setSpacing(10);
qx_id100059.setVerticalChildrenAlign("middle");
qx_id98069.add(qx_id100059);

var qx_id100068 = new qx.ui.basic.Image("icon/32/status/dialog-error.png");
qx_id100068.setDimension(32 ,32);
qx_id100059.add(qx_id100068);

var qx_id100072 = new qx.ui.basic.Label(this.tr(" "));
qx_id100072.setWrap(true);
qx_id100072.setHeight("100%");
qx_id100072.setWidth("1*");
qx_id100072.setMode("html");

qx.event.message.Bus.subscribe("qcl.databinding.messages.rpc.error",function(message){

  					var msg = message.getData() || "";
  					var msg = "" + msg.replace(/\\n/,"") + "";
  					this.setText(msg);
  				
},qx_id100072);
qx_id100059.add(qx_id100072);

var qx_id100095 = new qx.ui.layout.HorizontalBoxLayout();
qx_id100095.setWidth("100%");
qx_id100095.setHeight("auto");
qx_id100095.setHorizontalChildrenAlign("center");
qx_id100095.setSpacing(10);
qx_id98069.add(qx_id100095);

var qx_id100103 = new qx.ui.form.Button(this.tr("OK"),null);
qx_id100103.setHeight(25);
qx_id100103.setWidth(70);
qx_id100095.add(qx_id100103);

qx_id100103.addEventListener("execute", function(event){this.closeWindow(event,qx_id100103);},this);

/** end auto-generated gui code **/

      // set widget object, deprecated, will be removed
      this.setWidget(this);
    },

    /**
     * 
     * @param event {qx.event.type.Event}
     * @param target {qx.core.Target}
     */ 
    closeWindow : function(event,target)
    {

      this.close();
    
    }

  }

});


