<?xml version="1.0" encoding="UTF-8"?>
<!-- 

	QxTransformer
	Converts QXML to Javascript
	
	License: LGPL
	Autors: Siarhei Barysiuk <s.barysiuk@gmail.com>	
			Christian Boulanger <info@bibliograph.org>
	
	main file of QxTransformer hgkjhg
 -->
<!-- xml entities -->
<!DOCTYPE stylesheet [
	<!ENTITY CR '&#13;&#10;'>
	
	<!ENTITY USER_CONFIG_PATH 'config/user-config.xml'>
	<!ENTITY COMMONS_XSL_PATH 'common/common.xsl'>
	<!ENTITY LOGGING_XSL_PATH 'common/logging.xsl'>
	<!ENTITY WIDGETS_XSL_PATH 'widgets/widgets.xsl'>
	<!ENTITY TRANSFORMER_CONFIG_PATH 'config/transformer-config.xml'>
    <!ENTITY QXTRANSFORMER_VERSION '0.2'>
    <!ENTITY PREFIX 'qx_'>
	<!ENTITY DEBUG 'no'>
]>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
			xmlns:qx="http://www.qxtransformer.org/qooxdoo"
			xmlns:qxti="http://www.qxtransformer.org/internal"
			xmlns:qxt="http://www.qxtransformer.org/extension">
			

	<xsl:output method="html" indent="yes" encoding="UTF-8"/>
	<xsl:strip-space elements="*"/>
	
	<qxti:doc type="global">
		<qxti:info>
			The main stylesheet in project and so-called entry point.
			This stylesheet is provided to xsltproc for processing.
		</qxti:info>
	</qxti:doc>

	<!-- initialization -->
	<qxti:doc>
		<qxti:info>
			A path to a file with the settings of QxTransformer (paths, other).
		</qxti:info>
	</qxti:doc>
	<xsl:param name="transformerConfigXmlPath" select="'&TRANSFORMER_CONFIG_PATH;'"/> 
	
	<qxti:doc>
		<qxti:info>
			A path to a file with user settings such as qooxdoo version and others.
		</qxti:info>
	</qxti:doc>
	<xsl:param name="userConfigXmlPath" select="'&USER_CONFIG_PATH;'"/>
	
	<qxti:doc>
		<qxti:info>
			The configuration of QxTranformer (xml document). Used as global variables in order to get configuration parameters.
		</qxti:info>
	</qxti:doc>
	<xsl:variable name="transformerConfigDoc" select="document($transformerConfigXmlPath)"/>
	
	<qxti:doc>
		<qxti:info>
			The user settins (xml document). Used as global variables in order to get user parameters.
		</qxti:info>
	</qxti:doc>
	<xsl:variable name="userConfigDoc" select="document($userConfigXmlPath)"/>
		
	<!-- stylesheet includes -->
	<xsl:include href="&WIDGETS_XSL_PATH;"/>
	<xsl:include href="&COMMONS_XSL_PATH;"/>
	<xsl:include href="&LOGGING_XSL_PATH;"/>
	
	
	<!-- global variables -->
	<qxti:doc>
		<qxti:info>
			Contains version of QxTransformer.
		</qxti:info>
	</qxti:doc>
	<xsl:variable name="qxtransformerVersion" select="&QXTRANSFORMER_VERSION;"/>
	
	<qxti:doc>
		<qxti:info>
			A document with the description of widgets (the classes of widgets, constructor parameters, etc.). 
		</qxti:info>
	</qxti:doc>
	<xsl:variable name="tagsDoc" select="document($transformerConfigDoc/transformer-config/tags-path)"/>
	
	<qxti:doc>
		<qxti:info>
			A document containing mappings between name of widget (xml node) and processing template. 
		</qxti:info>
	</qxti:doc>
	<xsl:variable name="templatesMappingDoc" select="document($transformerConfigDoc/transformer-config/templates-mapping-path)"/>
	
	<qxti:doc>
		<qxti:info>
			ID of top widget in a document. 
		</qxti:info>
	</qxti:doc>
	<xsl:variable name="clientDocumentVar">
		<xsl:text>&PREFIX;</xsl:text>
		<xsl:value-of select="generate-id(/*/qx:*[1])"/>
	</xsl:variable>
	
	<qxti:doc>
		<qxti:info>
			TODO
		</qxti:info>
	</qxti:doc>
	<xsl:variable name="translateDocument" select="/*/qx:*[1]/@translate"/>
	
	<!-- processing user config, can be overridden by parameters passed trough xsl processor -->
	<qxti:doc>
		<qxti:info>
			The version of qooxdoo. Code will be generated by rules for this version.
			User defines this parameters in user configuration file but it can be overridden by input parameter.
		</qxti:info>
	</qxti:doc>
	<xsl:param name="qooxdooVersion" select="$userConfigDoc/config/qooxdooVersion"/>
	
	<qxti:doc>
		<qxti:info>
			The namespace of application.
			User defines this parameters in user configuration file but it can be overridden by input parameter.
		</qxti:info>
	</qxti:doc>
	<xsl:param name="applicationNamespace" select="$userConfigDoc/config/applicationNamespace"/>
	
	<qxti:doc>
		<qxti:info>
			Project root directory.
			User defines this parameters in user configuration file but it can be overridden by input parameter.
		</qxti:info>
	</qxti:doc>
	<xsl:param name="projectRootDir" select="$userConfigDoc/config/project-root-dir"/>
	
	<qxti:doc>
		<qxti:info>
			Defines whether debug information will be on console.
			Can be changed in project make file (variable ECHO).
		</qxti:info>
	</qxti:doc>
	<xsl:param name="echoOn" select="'true'"/>
	
	
</xsl:stylesheet>