/* ************************************************************************
   
   qooxdoo - the new era of web development
   
   http://qooxdoo.org
   
   Copyright:
     2006-2008 1&1 Internet AG, Germany, http://www.1and1.org
   
   License:
     LGPL: http://www.gnu.org/licenses/lgpl.html
     EPL: http://www.eclipse.org/org/documents/epl-v10.php
     See the LICENSE file in the project's top-level directory for details.
   
   Authors:
     * Michael Hartmeier (mlhartme)
   
 ************************************************************************ */

package org.qooxdoo.toolkit.plugin.binding.java;

import static org.junit.Assert.assertEquals;

import org.junit.Test;
import org.qooxdoo.toolkit.plugin.binding.java.Modifier;
import org.qooxdoo.toolkit.plugin.binding.java.Clazz;
import org.qooxdoo.toolkit.plugin.binding.java.ClazzType;
import org.qooxdoo.toolkit.plugin.binding.java.Method;
import org.qooxdoo.toolkit.plugin.binding.java.Field;
import org.qooxdoo.toolkit.plugin.binding.java.SimpleType;

public class DoctreeToJavaTest {
    @Test
    public void empty() throws Exception {
        check("/* Copyright (c) 1&1. All Rights Reserved. */\n" 
                + "\n" 
                + "// DO NOT EDIT - this file was generated by QWT. \n"
                + "\n" 
                + "package pkg;\n" 
                + "\n"
                + "/**\n"
                + " * 1.\n" 
                + " * @augment pkg.cn\n"
                + " */\n" 
                + "public class cn {\n"
                + "}\n",
                new Clazz(ClazzType.CLASS, "pkg.cn", null, "1."));
    }

    @Test
    public void htmlComment() throws Exception {
        String comment;
        
        comment = new Field("f", SimpleType.BOOLEAN, null, "<p>1</p><p>2</p>").comment(false);
        assertEquals("/**\n" +
                " * <p>1</p><p>2</p>\n" +
                " * @alias\n" +
                " */\n", comment);
    }

    @Test
    public void methodObject() throws Exception {
        StringBuilder builder;
        
        builder = new StringBuilder();
        new Method(Modifier.PRIVATE, false, false, false, false, SimpleType.STRING, "meth", null, null, null, "bd").toJava(builder);
        assertEquals("    private String meth() {\n"
                   + "bd" 
                   + "    }\n",
                     builder.toString());
    }

    @Test
    public void field() throws Exception {
        Clazz clazz;
        Field p;
        
        clazz = new Clazz(ClazzType.CLASS, "pkg.cn", null, null);
        p = new Field("str", SimpleType.STRING, null, null);
        clazz.addWithMethods(p);
        check(
                "/* Copyright (c) 1&1. All Rights Reserved. */\n" 
                        + "\n" 
                        + "// DO NOT EDIT - this file was generated by QWT. \n"
                        + "\n"
                        + "package pkg;\n"
                        + "\n"
                        + "/**\n"
                        + " * @augment pkg.cn\n"
                        + " */\n"
                        + "public class cn {\n"
                        + "    /**\n"
                        + "     * @alias\n"
                        + "     */\n"
                        + "    private String str;\n"
                        + "\n" 
                        + "    /**\n"
                        + "     * @alias\n"
                        + "     */\n" 
                        + "    public native String getStr();\n"
                        + "\n"
                        + "    /**\n"
                        + "     * @alias\n"
                        + "     */\n" 
                        + "    public native void setStr(String str);\n"
                        + "}\n",
                clazz);
    }

    private void check(String expected, Clazz clazz) throws Exception {
        StringBuilder builder;

        builder = new StringBuilder();
        clazz.toJava(builder);
        assertEquals(expected, builder.toString());
    }
}
