qcl sample application: qcl_jsonrpc_object Class Reference
qcl_jsonrpc_object Class Reference
Public Member Functions
__construct ()
& setSingleton ($instance)
& getSingleton ($classname)
configureService ()
set ($first, $value=null)
& get ($key)
& getResult ($key)
addMessage ($message, $data=true)
getServiceDirUrl ($append="")
raiseError ($message, $number=null, $file=null, $line=null)
debug ($var, $html=false)
Public Attributes
$error
$ini
$result = array()
Detailed Description
base class of all json rpc service classes
Definition at line 49 of file object.php.
Constructor & Destructor Documentation
qcl_jsonrpc_object::__construct ()
Class constructor, configures the service
Reimplemented from patched_object.
Reimplemented in qcl_auth_common, qcl_auth_permission, qcl_auth_role, qcl_auth_user, qcl_config, qcl_config_db, qcl_config_manager, qcl_db, qcl_db_pear, class_authConfig, class_role, class_user, and class_configManager.
Definition at line 79 of file object.php.
References configureService().
Member Function Documentation
& qcl_jsonrpc_object::setSingleton ($ instance)
set singleton instance of a class
Parameters:
object $instance reference to be set as singleton
Definition at line 89 of file object.php.
Referenced by class_user::__construct(), class_role::__construct(), and class_permission::__construct().
& qcl_jsonrpc_object::getSingleton ($ classname)
get singleton instance of class
Parameters:
string $classname
Returns:
object reference to singleton instance
Definition at line 103 of file object.php.
Referenced by class_configManager::__construct(), qcl_config_db::__construct(), class_user::__construct(), class_role::__construct(), and class_permission::__construct().
qcl_jsonrpc_object::configureService ()
reads initial configuration. looks for service.ini.php files, starting at the top-level service directory. lower-level service.ini.php files can override config directives selectively, inheriting the rest of the settings from the upper level config files.
Definition at line 120 of file object.php.
Referenced by __construct().
qcl_jsonrpc_object::set ($ first, $ value = null)
assemble a result array for the json response
Parameters:
mixed $first key or hash map of key-value pairs
mixed $value
Definition at line 146 of file object.php.
& qcl_jsonrpc_object::get ($ key)
gets value for particular result key
Reimplemented in qcl_config, and qcl_config_db.
Definition at line 166 of file object.php.
& qcl_jsonrpc_object::getResult ($ key)
gets result for json response
Definition at line 174 of file object.php.
Referenced by qcl_auth_user::method_addToRole(), qcl_auth_permission::method_addToRole(), qcl_auth_user::method_authenticate(), qcl_config_manager::method_create(), qcl_auth_common::method_create(), qcl_config_manager::method_delete(), qcl_auth_common::method_delete(), qcl_config_manager::method_getAll(), qcl_auth_common::method_getData(), class_authConfig::method_getPermissionNode(), class_authConfig::method_getRolesAndPermissions(), class_authConfig::method_getUserNode(), class_authConfig::method_getUsersAndRoles(), qcl_auth_user::method_logout(), qcl_auth_user::method_removeFromRole(), qcl_auth_permission::method_removeFromRole(), qcl_config_manager::method_set(), qcl_config_manager::method_update(), qcl_auth_common::method_update(), qcl_config_manager::method_updateClient(), and qcl_config_manager::method_updateServer().
qcl_jsonrpc_object::addMessage ($ message, $ data = true)
adds a server message
Parameters:
mixed $message Message name or hash map of messages
mixed $data Data dispatched with message
Definition at line 184 of file object.php.
Referenced by qcl_auth_user::method_addToRole(), qcl_auth_permission::method_addToRole(), qcl_auth_user::method_authenticate(), qcl_config_manager::method_create(), qcl_auth_common::method_create(), qcl_auth_common::method_delete(), qcl_auth_user::method_logout(), qcl_auth_user::method_removeFromRole(), qcl_auth_permission::method_removeFromRole(), qcl_config_manager::method_set(), qcl_config_manager::method_update(), and qcl_auth_common::method_update().
qcl_jsonrpc_object::getServiceDirUrl ($ append = "")
get service directory url
Definition at line 206 of file object.php.
qcl_jsonrpc_object::raiseError ($ message, $ number = null, $ file = null, $ line = null)
raises a server error and exits
Definition at line 216 of file object.php.
References $error.
Referenced by qcl_auth_user::addToRole(), qcl_auth_permission::addToRole(), qcl_db_pear::connect(), qcl_config_db::create(), qcl_db_pear::getAllRows(), qcl_auth_common::getByRef(), qcl_auth_common::getIdFromRef(), qcl_auth_user::getPermissions(), qcl_auth_role::getPermissions(), qcl_auth_user::getRoles(), qcl_db_pear::getRow(), qcl_config_db::getRowById(), qcl_auth_common::method_update(), qcl_db_pear::query(), qcl_auth_user::removeFromRole(), qcl_auth_permission::removeFromRole(), qcl_auth_user::requirePermission(), qcl_config_db::reset(), and qcl_config_db::set().
qcl_jsonrpc_object::debug ($ var, $ html = false)
debug a variable
Todo:
: debug to file
Definition at line 231 of file object.php.
Member Data Documentation
qcl_jsonrpc_object::$ini
initial configuration contained in ini.php-files in the # service class folders
See also:
qcl_jsonrpc_object::configureServie()
Definition at line 65 of file object.php.
qcl_jsonrpc_object::$result = array()
result value which will be serialized and returned to server
Definition at line 70 of file object.php.
Referenced by qcl_config_db::getAll(), qcl_auth_common::getAllNames(), qcl_auth_permission::getByRoleId(), qcl_auth_role::getByUserId(), qcl_auth_common::getIdFromRef(), qcl_auth_user::getPermissions(), qcl_auth_role::getPermissions(), qcl_auth_user::getRoles(), qcl_auth_common::method_getData(), class_authConfig::method_getPermissionNode(), class_authConfig::method_getRolesAndPermissions(), class_authConfig::method_getUserNode(), class_authConfig::method_getUsersAndRoles(), and qcl_config_manager::method_updateClient().
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/jsonrpc/object.php