qcl sample application: qcl_auth_permission Class Reference
qcl_auth_permission Class Reference
Public Member Functions
__construct ()
getByRoleId ($roleId=null)
addToRole ($permissionRefs, $roleRefs)
removeFromRole ($permissionRefs, $roleRefs)
method_addToRole ($params)
method_removeFromRole ($params)
Public Attributes
$table = "permissions"
$icon = "icon/16/mimetypes/empty-x-encrypted.png"
$nodeType = "qcl.auth.types.Permission"
$shortName = "permission"
$foreignKey = "permissionId"
Detailed Description
class providing data on permissions providing a backend to the qcl.auth client package
Class cannot be used directly, you need to subclass it in your application service class folder
Definition at line 11 of file permission.php.
Constructor & Destructor Documentation
qcl_auth_permission::__construct ()
constructor calls parent constructor for database intiatization
Reimplemented from qcl_auth_common.
Definition at line 31 of file permission.php.
Member Function Documentation
qcl_auth_permission::getByRoleId ($ roleId = null)
get a list of permissions for one or all roles
Parameters:
mixed $roleId null for all, array for a list of and integer for a single user id
Returns:
array An array, key: roleId, values: array of roleIds
Definition at line 45 of file permission.php.
References qcl_jsonrpc_object::$result.
qcl_auth_permission::addToRole ($ permissionRefs, $ roleRefs)
adds permission(s) to role(s)
Parameters:
mixed $permissionRefs (array or single value) permission ref(s) (id or namedId)
mixed $roleRef (array or single value) role refs (id or namedId)
Definition at line 69 of file permission.php.
References qcl_auth_common::getIdFromRef(), and qcl_jsonrpc_object::raiseError().
Referenced by method_addToRole().
qcl_auth_permission::removeFromRole ($ permissionRefs, $ roleRefs)
removes role(s) from permission(s)
Parameters:
mixed $permissionRefs (array or single value) permission ref(s) (id or namedId)
mixed $roleRef (array or single value) role refs (id or namedId)
Definition at line 100 of file permission.php.
References qcl_auth_common::getIdFromRef(), and qcl_jsonrpc_object::raiseError().
Referenced by method_removeFromRole().
qcl_auth_permission::method_addToRole ($ params)
add permission(s) to role(s)
Parameters:
null $param[0] not used
mixed $param[1] (array or number) permission refs (id or namedId)
mixed $param[2] (array or number) role refs (id or namedId)
Definition at line 138 of file permission.php.
References qcl_jsonrpc_object::addMessage(), addToRole(), and qcl_jsonrpc_object::getResult().
qcl_auth_permission::method_removeFromRole ($ params)
removes permission(s) from role(s)
Parameters:
null $param[0] not used
mixed $param[1] (array or number) permission refs (id or namedId)
mixed $param[2] (array or number) role refs (id or namedId)
Definition at line 156 of file permission.php.
References qcl_jsonrpc_object::addMessage(), qcl_jsonrpc_object::getResult(), and removeFromRole().
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/auth/permission.php