qcl sample application: class_authConfig Class Reference
class_authConfig Class Reference
Public Member Functions
__construct ()
method_getUsersAndRoles ($params)
method_getRolesAndPermissions ()
method_getPermissionNode ($params)
method_getUserNode ($params)
Detailed Description
Service class providing data to authConfig fronend
Definition at line 11 of file authConfig.php.
Constructor & Destructor Documentation
class_authConfig::__construct ()
constructor
Reimplemented from class_user.
Definition at line 25 of file authConfig.php.
Member Function Documentation
class_authConfig::method_getUsersAndRoles ($ params)
get treedatamodel of users and roles
Definition at line 37 of file authConfig.php.
References qcl_jsonrpc_object::$result, qcl_auth_common::getAll(), and qcl_jsonrpc_object::getResult().
class_authConfig::method_getRolesAndPermissions ()
get treedatamodel of roles and permissions
Definition at line 111 of file authConfig.php.
References qcl_jsonrpc_object::$result, and qcl_jsonrpc_object::getResult().
class_authConfig::method_getPermissionNode ($ params)
get individual permission node
Parameters:
$param[0] permission id
$param[1] parentNodeId
Returns:
array treedatamodel
Definition at line 188 of file authConfig.php.
References qcl_jsonrpc_object::$result, and qcl_jsonrpc_object::getResult().
class_authConfig::method_getUserNode ($ params)
get individual user node
Parameters:
$param[0] user id
$param[1] parentNodeId
Returns:
array treedatamodel
Definition at line 225 of file authConfig.php.
References qcl_jsonrpc_object::$result, qcl_auth_common::getById(), and qcl_jsonrpc_object::getResult().
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/sample_app/auth/authConfig.php