qcl sample application: qcl_auth_user Class Reference
qcl_auth_user Class Reference
Public Member Functions
__construct ()
getRoles ($userRef, $getNamedIds=true)
getRoleIds ($userRef)
getRoleNamedIds ($userRef)
getRoleRecords ($userRef)
getPermissions ($userRef, $getNamedIds=true)
authenticate ($username, $password)
getActiveUser ()
setActiveUser ($data)
getActiveUserId ()
hasPermission ($requestedPermission, $user=null)
requirePermission ($permission)
getSecurity ($username)
addToRole ($userRefs, $roleRefs)
removeFromRole ($userRefs, $roleRefs)
method_updateClient ($params)
method_authenticate ($params)
method_logout ()
method_addToRole ($params)
method_removeFromRole ($params)
Public Attributes
$table = "users"
$key_namedId = "username"
$key_username = "username"
$key_password = "password"
$icon = "icon/16/apps/system-users.png"
$nodeType = "qcl.auth.types.User"
$shortName = "user"
$foreignKey = "userId"
Detailed Description
class providing data on users providing a backend to the qcl.auth client package
Class cannot be used directly, you need to subclass it in your application service class folder
Definition at line 11 of file user.php.
Constructor & Destructor Documentation
qcl_auth_user::__construct ()
constructor calls parent constructor for database intiatization
Reimplemented from qcl_auth_common.
Reimplemented in class_authConfig, and class_user.
Definition at line 35 of file user.php.
Member Function Documentation
qcl_auth_user::getRoles ($ userRef, $ getNamedIds = true)
get list of roles (ids) that belong to a user
Parameters:
mixed $userRef user name or id
boolean $getNamedIds If true (default), get the names of the roles, If false, get ids If null, get whole records
Returns:
array Array of string names or numeric ids
Definition at line 53 of file user.php.
References qcl_jsonrpc_object::$result, qcl_auth_common::getIdFromRef(), and qcl_jsonrpc_object::raiseError().
Referenced by getPermissions(), getRoleIds(), getRoleNamedIds(), getRoleRecords(), getSecurity(), and class_user::method_getRoles().
qcl_auth_user::getRoleIds ($ userRef)
get ids of user roles
Definition at line 99 of file user.php.
References getRoles().
qcl_auth_user::getRoleNamedIds ($ userRef)
get named ids of user roles
Definition at line 107 of file user.php.
References getRoles().
qcl_auth_user::getRoleRecords ($ userRef)
get full records of user roles
Definition at line 115 of file user.php.
References getRoles().
qcl_auth_user::getPermissions ($ userRef, $ getNamedIds = true)
get list of permission (ids) that belong to a user
Parameters:
mixed $userRef user name or id
boolean $getNamedIds If true (default), get the names of the roles, if null, get the whole records, otherwise just ids
Returns:
array Array of string names or numeric ids
Definition at line 128 of file user.php.
References qcl_jsonrpc_object::$result, qcl_auth_common::getIdFromRef(), getRoles(), and qcl_jsonrpc_object::raiseError().
Referenced by hasPermission(), and class_user::method_getPermissions().
qcl_auth_user::authenticate ($ username, $ password)
authenticate a user with a password
Parameters:
string $username
string $password (MD5-encoded) password
Definition at line 154 of file user.php.
References qcl_auth_common::getByName(), and setActiveUser().
Referenced by method_authenticate().
qcl_auth_user::getActiveUser ()
gets active user information which is persisted during a session
Returns:
array
Definition at line 187 of file user.php.
Referenced by hasPermission(), and method_authenticate().
qcl_auth_user::setActiveUser ($ data)
sets active user information
Parameters:
array map with user data
Definition at line 196 of file user.php.
Referenced by authenticate(), method_authenticate(), and method_logout().
qcl_auth_user::getActiveUserId ()
gets active user record id
Returns:
int
Definition at line 205 of file user.php.
qcl_auth_user::hasPermission ($ requestedPermission, $ user = null)
checks if active user has the given permission respects wildcards, i.e. myapp.permissions.* covers myapp.permissions.canDoFoo
Parameters:
string $requestedPermission the permission to check
string $user (optional) if given, check this user's permissions. Otherwise check the active user's permissions
Definition at line 218 of file user.php.
References getActiveUser(), qcl_auth_common::getByName(), and getPermissions().
Referenced by class_user::method_hasPermission(), and requirePermission().
qcl_auth_user::requirePermission ($ permission)
requires a specific permission if active user does not have the permission, abort with an error
Definition at line 247 of file user.php.
References hasPermission(), and qcl_jsonrpc_object::raiseError().
Referenced by method_addToRole(), and method_removeFromRole().
qcl_auth_user::getSecurity ($ username)
gets userdata and security policies
Parameters:
string username
Returns:
array security policy and user data
Definition at line 264 of file user.php.
References qcl_auth_common::getByName(), and getRoles().
Referenced by method_authenticate().
qcl_auth_user::addToRole ($ userRefs, $ roleRefs)
add user(s) to role(s)
Parameters:
mixed $userRefs (array or number) user ref(s) (id or namedId)
mixed $roleRefs (array or number) role refs (id or namedId)
Definition at line 296 of file user.php.
References qcl_auth_common::getIdFromRef(), and qcl_jsonrpc_object::raiseError().
Referenced by method_addToRole().
qcl_auth_user::removeFromRole ($ userRefs, $ roleRefs)
removes user(s) from role(s)
Parameters:
mixed $userRefs (array or number) user ref(s) (id or namedId)
mixed $roleRefs (array or number) role refs (id or namedId)
Definition at line 329 of file user.php.
References qcl_auth_common::getIdFromRef(), and qcl_jsonrpc_object::raiseError().
Referenced by method_removeFromRole().
qcl_auth_user::method_updateClient ($ params)
default update client method: authenticate user
Definition at line 366 of file user.php.
References method_authenticate().
qcl_auth_user::method_authenticate ($ params)
default update client method: authenticate user
Parameters:
string $param[0] username
string $param[1] (MD5-encoded) password
Definition at line 376 of file user.php.
References qcl_jsonrpc_object::addMessage(), authenticate(), getActiveUser(), qcl_jsonrpc_object::getResult(), getSecurity(), and setActiveUser().
Referenced by method_updateClient().
qcl_auth_user::method_logout ()
logout current user
Definition at line 409 of file user.php.
References qcl_jsonrpc_object::addMessage(), qcl_jsonrpc_object::getResult(), and setActiveUser().
qcl_auth_user::method_addToRole ($ params)
add user(s) to role(s)
Parameters:
null $param[0] not used
mixed $param[1] (array or number) user refs (id or namedId)
mixed $param[2] (array or number) role refs (id or namedId)
Definition at line 422 of file user.php.
References qcl_jsonrpc_object::addMessage(), addToRole(), qcl_jsonrpc_object::getResult(), and requirePermission().
qcl_auth_user::method_removeFromRole ($ params)
removes user(s) from role(s)
Parameters:
null $param[0] not used
mixed $param[1] (array or number) user refs (id or namedId)
mixed $param[2] (array or number) role refs (id or namedId)
Definition at line 440 of file user.php.
References qcl_jsonrpc_object::addMessage(), qcl_jsonrpc_object::getResult(), removeFromRole(), and requirePermission().
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/auth/user.php