qcl sample application: qcl_auth_role Class Reference
qcl_auth_role Class Reference
Public Member Functions
__construct ()
getPermissions ($roleRef, $getNamedIds=true)
getByUserId ($userId=null)
Public Attributes
$table = "roles"
$icon = "icon/16/apps/system-users.png"
$nodeType = "qcl.auth.types.Role"
$shortName = "role"
$foreignKey = "roleId"
Detailed Description
class providing data on roles providing a backend to the qcl.auth client package
Class cannot be used directly, you need to subclass it in your application service class folder
Definition at line 11 of file role.php.
Constructor & Destructor Documentation
qcl_auth_role::__construct ()
constructor calls parent constructor for database intiatization
Reimplemented from qcl_auth_common.
Reimplemented in class_role.
Definition at line 31 of file role.php.
Member Function Documentation
qcl_auth_role::getPermissions ($ roleRef, $ getNamedIds = true)
get list of permission (ids) that belong to a role
Parameters:
mixed $roleRef role name or id
boolean $getNamedIds If true (default), get the names of the permissions, if null, return all the whole rows , otherwise just ids
Returns:
array Array of string names or numeric ids
Definition at line 49 of file role.php.
References qcl_jsonrpc_object::$result, qcl_auth_common::getIdFromRef(), and qcl_jsonrpc_object::raiseError().
Referenced by class_role::method_getPermissions().
qcl_auth_role::getByUserId ($ userId = null)
get a list of roles for one or all user
Parameters:
mixed $userId null for all, array for a list of and integer for a single user id
Returns:
array An array, key: userId, values: array of roleIds
Definition at line 96 of file role.php.
References qcl_jsonrpc_object::$result.
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/auth/role.php