qcl sample application: qcl_jsonrpc_db_pear Class Reference
qcl_jsonrpc_db_pear Class Reference
Public Member Functions
__construct ()
& connect ()
& query ($sql)
& execute ($sql)
& getRow ($sql)
& getAllRows ($sql)
insert ($table, $data)
update ($table, $data, $idColumn="id")
delete ($table, $ids, $idColumn="id")
escape ($string)
getLastInsertId ()
disconnect ()
Detailed Description
Base class for rpc objects which do database queries relying on PEAR::DB for database access
Definition at line 10 of file pear.php.
Constructor & Destructor Documentation
qcl_jsonrpc_db_pear::__construct ()
constructor
Reimplemented from qcl_jsonrpc_db.
Reimplemented in qcl_jsonrpc_config_db.
Definition at line 16 of file pear.php.
Member Function Documentation
& qcl_jsonrpc_db_pear::connect ()
connects to database
Reimplemented from qcl_jsonrpc_db.
Definition at line 25 of file pear.php.
References qcl_jsonrpc_db::$db, and qcl_jsonrpc_object::raiseError().
& qcl_jsonrpc_db_pear::query ($ sql)
queries database
Reimplemented from qcl_jsonrpc_db.
Definition at line 50 of file pear.php.
References qcl_jsonrpc_object::$error, and qcl_jsonrpc_object::raiseError().
Referenced by delete(), execute(), insert(), and update().
& qcl_jsonrpc_db_pear::execute ($ sql)
executes a query, alias of $this->query
Reimplemented from qcl_jsonrpc_db.
Definition at line 63 of file pear.php.
References query().
Referenced by qcl_jsonrpc_config_db::set().
& qcl_jsonrpc_db_pear::getRow ($ sql)
get first row of result set
Reimplemented from qcl_jsonrpc_db.
Definition at line 71 of file pear.php.
References qcl_jsonrpc_object::raiseError().
& qcl_jsonrpc_db_pear::getAllRows ($ sql)
gets resultset mapped to array
Reimplemented from qcl_jsonrpc_db.
Definition at line 83 of file pear.php.
References qcl_jsonrpc_object::raiseError().
qcl_jsonrpc_db_pear::insert ($ table, $ data)
inserts a record into a table and returns last_insert_id()
Parameters:
string $table table name
array $data associative array with the column names as keys and the column data as values
Returns:
int the id of the inserted row (only if auto_incremnt-key)
Reimplemented from qcl_jsonrpc_db.
Definition at line 98 of file pear.php.
References escape(), getLastInsertId(), and query().
qcl_jsonrpc_db_pear::update ($ table, $ data, $ idColumn = "id")
updates a record in a table identified by id
Parameters:
string $table table name
array $data associative array with the column names as keys and the column data as values
string $idColumn name of column containing the record id
Reimplemented from qcl_jsonrpc_db.
Definition at line 130 of file pear.php.
References escape(), and query().
qcl_jsonrpc_db_pear::delete ($ table, $ ids, $ idColumn = "id")
deletes a record in a table identified by id
Parameters:
string $table table name
mixed $ids (array of) record id(s)
string $idColumn name of column containing the record id
Reimplemented from qcl_jsonrpc_db.
Definition at line 156 of file pear.php.
References query().
qcl_jsonrpc_db_pear::escape ($ string)
escapes strings for use in sql queries
Reimplemented from qcl_jsonrpc_db.
Definition at line 168 of file pear.php.
Referenced by insert(), and update().
qcl_jsonrpc_db_pear::getLastInsertId ()
gets last inserted primary key
Reimplemented from qcl_jsonrpc_db.
Definition at line 176 of file pear.php.
Referenced by insert(), and qcl_jsonrpc_config_db::set().
qcl_jsonrpc_db_pear::disconnect ()
disconnects from database
Reimplemented from qcl_jsonrpc_db.
Definition at line 185 of file pear.php.
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/jsonrpc/db/pear.php