/**
    Generated by QxTransformer v.0.4.
    Author Christian Boulanger
**/

/*------------------------------------------------------------------------------

------------------------------------------------------------------------------*/
qx.Class.define("access.components.Footer",
{
      extend: qx.ui.groupbox.GroupBox,
  
  
  
      construct: function() {
        this.base(arguments);
        this.__qxtCreateUI();
    },

    members : { 
        __qxtCreateUI : function() {
            

    //connecting autogenerated id with 'this'
    var qxGroupBox1 = this;


    qxGroupBox1.setLegend("Source");
 
    


    

    var qxHbox1 = new qx.ui.layout.HBox(5, null, null);
    


    qxHbox1.setSpacing(5);
 
    

    qxGroupBox1.setLayout(qxHbox1);

    

    var qxButton1 = new qx.ui.form.Button("SVN", null, null);
    


    qxButton1.setLabel("SVN");
 
    

    

qxGroupBox1.add(qxButton1 );

    
qxButton1.addListener("execute",     function(        e      ) {
        
          window.open("https://qooxdoo-contrib.svn.sourceforge.net/svnroot/qooxdoo-contrib/trunk/qooxdoo-contrib/qcl/trunk/demo/access/");
        
    }, this);














	


    var qxButton2 = new qx.ui.form.Button("Tutorial", null, null);
    


    qxButton2.setLabel("Tutorial");
 
    

    

qxGroupBox1.add(qxButton2 );

    
qxButton2.addListener("execute",     function(        e      ) {
        
          window.open("http://qooxdoo.org/contrib/project/qcl/tutorial_application");
        
    }, this);














	


    var qxButton3 = new qx.ui.form.Button("Application JS source", null, null);
    


    qxButton3.setLabel("Application JS source");
 
    

    

qxGroupBox1.add(qxButton3 );

    
qxButton3.addListener("execute",     function(        e      ) {
        
          window.open("../source/class/access/Main.js");
        
    }, this);














	


    var qxButton4 = new qx.ui.form.Button("Toolbar XML source", null, null);
    


    qxButton4.setLabel("Toolbar XML source");
 
    

    

qxGroupBox1.add(qxButton4 );

    
qxButton4.addListener("execute",     function(        e      ) {
        
          window.open("../source/class/access/components/ToolBar.xml");
        
    }, this);














	


    var qxButton5 = new qx.ui.form.Button("Toolbar Js source", null, null);
    


    qxButton5.setLabel("Toolbar Js source");
 
    

    

qxGroupBox1.add(qxButton5 );

    
qxButton5.addListener("execute",     function(        e      ) {
        
          window.open("../source/class/access/components/ToolBar.js");
        
    }, this);














	


    var qxButton6 = new qx.ui.form.Button("Body XML source", null, null);
    


    qxButton6.setLabel("Body XML source");
 
    

    

qxGroupBox1.add(qxButton6 );

    
qxButton6.addListener("execute",     function(        e      ) {
        
          window.open("../source/class/access/components/Body.xml");
        
    }, this);














	


    var qxButton7 = new qx.ui.form.Button("Body JS source", null, null);
    


    qxButton7.setLabel("Body JS source");
 
    

    

qxGroupBox1.add(qxButton7 );

    
qxButton7.addListener("execute",     function(        e      ) {
        
          window.open("../source/class/access/components/Body.js");
        
    }, this);














	








	








	

        }
        
    }






});






