/* ************************************************************************


    Widget class 'qcl.components.jsonrpc.ErrorWindow'.
    This file is auto-generated. Do not edit, manual changes will be overwritten.


    qooxdoo v.0.7 code generated by QxTransformer v.

************************************************************************ */


/* ************************************************************************


************************************************************************ */

/**
 * @todo: add documentation here auto-generated from qxml file
 */
qx.Class.define("qcl.components.jsonrpc.ErrorWindow",
{
  extend : qx.ui.window.Window,

    
  /**
   * widget property, is deprecated and will be removed
   * @deprecated
   */
  properties : {
        widget : { check : "Object" }
  },
    
  /**
   * Constructor
   */
  construct : function()
  {
    // call parent class
    this.base(arguments);

    //call paint method to draw widget
    this.paint();
  },


  members :
  {

    /**
     * Draw widget
     */
    paint: function ()
    {
      // Client document object
      var qx_id97124 = qx.ui.core.ClientDocument.getInstance();

/** begin auto-generated gui code **/

this.setWidth(400);
this.setHeight("auto");
this.setCaption(this.tr("Error"));
this.setShowMinimize(false);
this.setShowMaximize(false);
this.setShowClose(false);

this.addEventListener("appear",function(event)
{
this.centerToBrowser()
},this);

qx.event.message.Bus.subscribe("qcl.databinding.messages.rpc.error",function(message){

      message.getData() == false ? this.hide() : this.show();
    
},this);

var qx_id98205 = new qx.ui.layout.VerticalBoxLayout();
qx_id98205.setSpacing(5);
qx_id98205.setPadding(10);
qx_id98205.setWidth("100%");
qx_id98205.setHeight("100%");
this.add(qx_id98205);

var qx_id100206 = new qx.ui.layout.HorizontalBoxLayout();
qx_id100206.setWidth("100%");
qx_id100206.setHeight("1*");
qx_id100206.setSpacing(10);
qx_id100206.setVerticalChildrenAlign("middle");
qx_id98205.add(qx_id100206);

var qx_id100215 = new qx.ui.basic.Image("icon/32/status/dialog-error.png");
qx_id100215.setDimension(32 ,32);
qx_id100206.add(qx_id100215);

var qx_id100220 = new qx.ui.basic.Label(this.tr(" "));
qx_id100220.setWrap(true);
qx_id100220.setHeight("100%");
qx_id100220.setWidth("1*");
qx_id100220.setMode("html");

qx.event.message.Bus.subscribe("qcl.databinding.messages.rpc.error",function(message){

            var msg = message.getData() || "";
            var msg = "" + msg.replace(/\\n/,"") + "";
            this.setText(msg);
          
},qx_id100220);
qx_id100206.add(qx_id100220);

var qx_id100242 = new qx.ui.layout.HorizontalBoxLayout();
qx_id100242.setWidth("100%");
qx_id100242.setHeight("auto");
qx_id100242.setHorizontalChildrenAlign("center");
qx_id100242.setSpacing(10);
qx_id98205.add(qx_id100242);

var qx_id100251 = new qx.ui.form.Button(this.tr("OK"),null);
qx_id100251.setHeight(25);
qx_id100251.setWidth(70);
qx_id100242.add(qx_id100251);

qx_id100251.addEventListener("execute", function(event){this.closeWindow(event,qx_id100251);},this);

/** end auto-generated gui code **/

      // set widget object, deprecated, will be removed
      this.setWidget(this);
    },

    /**
     * 
     * @param event {qx.event.type.Event}
     * @param target {qx.core.Target}
     */ 
    closeWindow : function(event,target)
    {

      this.close();
    
    }

  }

});


