/* ************************************************************************


    Widget class 'qcl.components.jsonrpc.ServerProcessStatusBar'.
    This file is auto-generated. Do not edit, manual changes will be overwritten.


    qooxdoo v.0.7 code generated by QxTransformer v.

************************************************************************ */


/* ************************************************************************
#embed(qx.icontheme/16/actions/dialog-cancel.png)


************************************************************************ */

/**
 * @todo: add documentation here auto-generated from qxml file
 */
qx.Class.define("qcl.components.jsonrpc.ServerProcessStatusBar",
{
  extend : qx.ui.layout.HorizontalBoxLayout,

  include : [ qcl.components.jsonrpc.ServerProcessStatus ],

    
  /**
   * widget property, is deprecated and will be removed
   * @deprecated
   */
  properties : {
        widget : { check : "Object" }
  },
    
  /**
   * Constructor
   */
  construct : function()
  {
    // call parent class
    this.base(arguments);

    //call paint method to draw widget
    this.paint();
  },


  members :
  {

    /**
     * Draw widget
     */
    paint: function ()
    {
      // Client document object
      var qx_id97222 = qx.ui.core.ClientDocument.getInstance();

/** begin auto-generated gui code **/

this.setWidth("100%");
this.setHeight("auto");
this.setSpacing(5);
this.setPadding(3);

this.addEventListener("displayServerMessage", function(event){this.handleDisplayServerMessage(event,this);},this);

this.addEventListener("endProcess", function(event){this.handleEnd(event,this);},this);

this.displayLabel = new qx.ui.basic.Label(this.tr(" "));
this.displayLabel.setWrap(true);
this.displayLabel.setHeight("100%");
this.displayLabel.setWidth("1*");
this.displayLabel.setMode("html");
this.add(this.displayLabel);

var qx_id100266 = new qx.ui.form.Button(this.tr("Cancel"),"icon/16/actions/dialog-cancel.png");
qx_id100266.setWidth("auto");
qx_id100266.setHeight(25);
this.add(qx_id100266);

qx_id100266.addEventListener("execute", function(event){this.handleEnd(event,qx_id100266);},this);

/** end auto-generated gui code **/

      // set widget object, deprecated, will be removed
      this.setWidget(this);
    }

  }

});


