/* ************************************************************************


    Widget class 'qcl.components.jsonrpc.ErrorWindow'.
    This file is auto-generated. Do not edit, manual changes will be overwritten.


    qooxdoo v.0.7 code generated by QxTransformer v.

************************************************************************ */


/* ************************************************************************


************************************************************************ */

/**
 * @todo: add documentation here auto-generated from qxml file
 */
qx.Class.define("qcl.components.jsonrpc.ErrorWindow",
{
  extend : qx.ui.window.Window,

    
  /**
   * widget property, is deprecated and will be removed
   * @deprecated
   */
  properties : {
        widget : { check : "Object" }
  },
    
  /**
   * Constructor
   */
  construct : function()
  {
    // call parent class
    this.base(arguments);

    //call paint method to draw widget
    this.paint();
  },


  members :
  {

    /**
     * Draw widget
     */
    paint: function ()
    {
      // Client document object
      var qx_id97222 = qx.ui.core.ClientDocument.getInstance();

/** begin auto-generated gui code **/

this.setWidth(400);
this.setHeight("auto");
this.setCaption(this.tr("Error"));
this.setShowMinimize(false);
this.setShowMaximize(false);
this.setShowClose(false);

this.addEventListener("appear",function(event)
{
this.centerToBrowser()
},this);

qx.event.message.Bus.subscribe("qcl.databinding.messages.rpc.error",function(message){

      message.getData() == false ? this.hide() : this.show();
    
},this);

var qx_id98304 = new qx.ui.layout.VerticalBoxLayout();
qx_id98304.setSpacing(5);
qx_id98304.setPadding(10);
qx_id98304.setWidth("100%");
qx_id98304.setHeight("100%");
this.add(qx_id98304);

var qx_id100302 = new qx.ui.layout.HorizontalBoxLayout();
qx_id100302.setWidth("100%");
qx_id100302.setHeight("1*");
qx_id100302.setSpacing(10);
qx_id100302.setVerticalChildrenAlign("middle");
qx_id98304.add(qx_id100302);

var qx_id100311 = new qx.ui.basic.Image("icon/32/status/dialog-error.png");
qx_id100311.setDimension(32 ,32);
qx_id100302.add(qx_id100311);

var qx_id100316 = new qx.ui.basic.Label(this.tr(" "));
qx_id100316.setWrap(true);
qx_id100316.setHeight("100%");
qx_id100316.setWidth("1*");
qx_id100316.setMode("html");

qx.event.message.Bus.subscribe("qcl.databinding.messages.rpc.error",function(message){

            var msg = message.getData() || "";
            var msg = "" + msg.replace(/\\n/,"") + "";
            this.setText(msg);
          
},qx_id100316);
qx_id100302.add(qx_id100316);

var qx_id100338 = new qx.ui.layout.HorizontalBoxLayout();
qx_id100338.setWidth("100%");
qx_id100338.setHeight("auto");
qx_id100338.setHorizontalChildrenAlign("center");
qx_id100338.setSpacing(10);
qx_id98304.add(qx_id100338);

var qx_id100347 = new qx.ui.form.Button(this.tr("OK"),null);
qx_id100347.setHeight(25);
qx_id100347.setWidth(70);
qx_id100338.add(qx_id100347);

qx_id100347.addEventListener("execute", function(event){this.closeWindow(event,qx_id100347);},this);

/** end auto-generated gui code **/

      // set widget object, deprecated, will be removed
      this.setWidget(this);
    },

    /**
     * 
     * @param event {qx.event.type.Event}
     * @param target {qx.core.Target}
     */ 
    closeWindow : function(event,target)
    {

      this.close();
    
    }

  }

});


