/**
 * Generated by QxTransformer v.0.4. 
 * Author Christian Boulanger
 */

/*------------------------------------------------------------------------------
 #asset(qx/icon/${qx.icontheme}/16/status/dialog-password.png)
 #asset(qx/icon/${qx.icontheme}/22/apps/preferences-users.png)
 #asset(qx/icon/${qx.icontheme}/16/actions/application-exit.png)

 ------------------------------------------------------------------------------*/
qx.Class.define("access.components.ToolBar", {
			extend : qx.ui.toolbar.ToolBar,

			construct : function() {
				this.base(arguments);
				this.__qxtCreateUI();
			},

			members : {
				__qxtCreateUI : function() {

					// connecting autogenerated id with 'this'
					var qxToolBar1 = this;

					var qxToolBarPart1 = new qx.ui.toolbar.Part();

					qxToolBar1.add(qxToolBarPart1);

					var loginButton = new qx.ui.toolbar.Button("Login",
							"icon/16/status/dialog-password.png", null);

					loginButton.setLabel("Login");
					loginButton.setVisibility("excluded");
					loginButton.setIcon("icon/16/status/dialog-password.png");

					qxToolBarPart1.add(loginButton);

					this.getApplication().bind(
							"accessManager.authenticatedUser", loginButton,
							"visibility", {
								converter : function(v) {
									return v ? 'excluded' : 'visible'
								}
							});
					loginButton.addListener("execute", function(e) {

								this.getApplication()
										.getWidgetById("loginDialog").show();

							}, this);

					var logoutButton = new qx.ui.toolbar.Button("Logout",
							"icon/16/actions/application-exit.png", null);

					logoutButton.setLabel("Logout");
					logoutButton.setVisibility("excluded");
					logoutButton
							.setIcon("icon/16/actions/application-exit.png");

					qxToolBarPart1.add(logoutButton);

					this.getApplication().bind(
							"accessManager.authenticatedUser", logoutButton,
							"visibility", {
								converter : function(v) {
									return v ? 'visible' : 'excluded'
								}
							});
					logoutButton.addListener("execute", function(e) {

								this.getApplication().logout();

							}, this);

					var qxAtom1 = new qx.ui.basic.Atom("Loading...",
							"icon/22/apps/preferences-users.png");

					qxAtom1.setLabel("Loading...");
					qxAtom1.setIcon("icon/22/apps/preferences-users.png");

					qxToolBarPart1.add(qxAtom1);

					this.getApplication().bind(
							"accessManager.userManager.activeUser.fullname",
							qxAtom1, "label", {});

					var qxToolBarPart2 = new qx.ui.toolbar.Part();

					qxToolBar1.add(qxToolBarPart2);

					var qxToolBarMenuButton1 = new qx.ui.toolbar.MenuButton(
							"Server", null, null);

					qxToolBarMenuButton1.setLabel("Server");

					qxToolBarPart2.add(qxToolBarMenuButton1);

					var qxMenu1 = new qx.ui.menu.Menu();

					qxToolBarMenuButton1.setMenu(qxMenu1);

					var qxRadioGroup1 = new qx.ui.form.RadioGroup();

					var qxMenuRadioButton1 = new qx.ui.menu.RadioButton(
							"Use RpcPhp server", null);

					qxMenuRadioButton1.setModel("rpcphp");
					qxMenuRadioButton1.setLabel("Use RpcPhp server");

					qxRadioGroup1.add(qxMenuRadioButton1);

					qxMenu1.add(qxMenuRadioButton1);

					var qxMenuRadioButton2 = new qx.ui.menu.RadioButton(
							"Use qcl server", null);

					qxMenuRadioButton2.setModel("qcl");
					qxMenuRadioButton2.setLabel("Use qcl server");

					qxRadioGroup1.add(qxMenuRadioButton2);

					qxMenu1.add(qxMenuRadioButton2);

					qxRadioGroup1.addListener("changeSelection", function(e) {

								this.getApplication().setServer(e.getData()[0]
										.getModel());

							}, this);

				}

			}

		});
