/**
    Generated by QxTransformer v.0.4.
    Author Christian Boulanger
**/

/*------------------------------------------------------------------------------

#require(qx.*)
#require(qcl.databinding.event.*)
------------------------------------------------------------------------------*/
qx.Class.define("access.components.MainToolBar",
{
      extend: qx.ui.toolbar.ToolBar,
  
  
  
      construct: function() {
        this.base(arguments);
        this.__qxtCreateUI();
    },

    members : { 
        __qxtCreateUI : function() {
            

    //connecting autogenerated id with 'this'
    var qxToolBar1 = this;


    
    


    

    var qxToolBarPart1 = new qx.ui.toolbar.Part();
    


    
    

    qxToolBar1.add(qxToolBarPart1);

    

    var qxToolBarButton1 = new qx.ui.toolbar.Button("Anonymous", null, null);
    


    qxToolBarButton1.setEnabled(true);
 qxToolBarButton1.setLabel("Anonymous");
 
    

    qxToolBarPart1.add(qxToolBarButton1);

    qxToolBarButton1.addListener("execute",     function(e) {
        
          alert("This button is for everybody!");
        
    } );














	


    var qxToolBarButton2 = new qx.ui.toolbar.Button("User", null, null);
    


    qxToolBarButton2.setEnabled(false);
 qxToolBarButton2.setLabel("User");
 
    

    qxToolBarPart1.add(qxToolBarButton2);

    







	


    var qxToolBarButton3 = new qx.ui.toolbar.Button("Admin", null, null);
    


    qxToolBarButton3.setEnabled(false);
 qxToolBarButton3.setLabel("Admin");
 
    

    qxToolBarPart1.add(qxToolBarButton3);

    







	








	


    var qxToolBarPart2 = new qx.ui.toolbar.Part();
    


    
    

    qxToolBar1.add(qxToolBarPart2);

    

    var qxToolBarCheckBox1 = new qx.ui.toolbar.CheckBox("Foo Button", null, null);
    


    qxToolBarCheckBox1.setWidgetId("fooButton");
 qxToolBarCheckBox1.setLabel("Foo Button");
 
    

    qxToolBarPart2.add(qxToolBarCheckBox1);

    
qcl.config.Manager.getInstance().addListener("ready",function(){       
  qcl.config.Manager.getInstance().bindValue("test.checked",qxToolBarCheckBox1, "value" );      
});
   







	


    var qxCheckBox1 = new qx.ui.form.CheckBox("Foo 2");
    


    qxCheckBox1.setWidgetId("fooCheckBox");
 qxCheckBox1.setLabel("Foo 2");
 
    

    
qxToolBarPart2.add(qxCheckBox1 );

    
qcl.config.Manager.getInstance().addListener("ready",function(){       
  qcl.config.Manager.getInstance().bindValue("test.checked",qxCheckBox1, "value" );      
});
   







	








	








	

        }
        
    }






});






