QOOXDOO_PATH = ../qooxdoo-0.7.3-sdk
QXTRANSFORMER_PATH = .

include $(QOOXDOO_PATH)/frontend/framework/tool/make/targets.mk
include $(QOOXDOO_PATH)/frontend/framework/tool/make/application.mk
include $(QXTRANSFORMER_PATH)/tool/qxtransformer.mk

error:
	@echo "  * Please configure QOOXDOO_PATH"
