qcl sample application: qcl_db Class Reference
qcl_db Class Reference
Public Member Functions
__construct ()
& getSubclass ($ini)
& connect ()
& query ($sql)
& execute ($sql)
& getRow ($sql)
& getAllRows ($sql)
insert ($table, $data)
update ($table, $data, $idColumn)
delete ($table, $data, $idColumn)
escape ($string)
getLastInsertId ()
disconnect ()
__destruct ()
Public Attributes
$db
$dsn
Detailed Description
abstract class for rpc objects which do database queries implemented by subclasses with specific database adapters
Definition at line 9 of file db.php.
Constructor & Destructor Documentation
qcl_db::__construct ()
constructor, reads database configuration
Reimplemented from qcl_jsonrpc_object.
Reimplemented in qcl_db_pear.
Definition at line 25 of file db.php.
References connect().
qcl_db::__destruct ()
destructor, disconnects from database
Definition at line 122 of file db.php.
References disconnect().
Member Function Documentation
& qcl_db::getSubclass ($ ini)
static method which returns a database object based on the configuration file
Parameters:
array $ini initial configuration array
Returns:
always returns a PEAR object at the moment
Definition at line 41 of file db.php.
References $db.
Referenced by qcl_config_db::__construct(), and qcl_auth_common::__construct().
& qcl_db::connect ()
makes connection
Reimplemented in qcl_db_pear.
Definition at line 60 of file db.php.
Referenced by __construct().
& qcl_db::query ($ sql)
queries database
Reimplemented in qcl_db_pear.
Definition at line 65 of file db.php.
& qcl_db::execute ($ sql)
executes a query, alias of $this->query
Reimplemented in qcl_db_pear.
Definition at line 70 of file db.php.
& qcl_db::getRow ($ sql)
get first row of result set
Reimplemented in qcl_db_pear.
Definition at line 75 of file db.php.
& qcl_db::getAllRows ($ sql)
gets whole result set mapped to array
Reimplemented in qcl_db_pear.
Definition at line 80 of file db.php.
qcl_db::insert ($ table, $ data)
inserts a record into a table and returns last_insert_id()
Parameters:
string $table table name
array $data associative array with the column names as keys and the column data as values
Reimplemented in qcl_db_pear.
Definition at line 87 of file db.php.
qcl_db::update ($ table, $ data, $ idColumn)
updates a record in a table identified by id
Parameters:
string $table table name
array $data associative array with the column names as keys and the column data as values
string $idColumn name of column containing the record id
Reimplemented in qcl_db_pear.
Definition at line 95 of file db.php.
qcl_db::delete ($ table, $ data, $ idColumn)
deletes a record in a table identified by id
Parameters:
string $table table name
string $idColumn name of column containing the record id
Reimplemented in qcl_db_pear.
Definition at line 102 of file db.php.
qcl_db::escape ($ string)
escapes strings for use in sql queries
Reimplemented in qcl_db_pear.
Definition at line 107 of file db.php.
qcl_db::getLastInsertId ()
gets last inserted primary key
Reimplemented in qcl_db_pear.
Definition at line 112 of file db.php.
qcl_db::disconnect ()
disconnects from database
Reimplemented in qcl_db_pear.
Definition at line 117 of file db.php.
Referenced by __destruct().
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/db/db.php