qcl sample application: qcl_auth_common Class Reference
qcl_auth_common Class Reference
Public Member Functions
__construct ()
getIdFromRef ($ref)
getAll ($orderBy=null)
getById ($id)
getByName ($name)
getByRef ($ref)
getDescriptiveName ($ref)
getAllNames ()
insert ($row)
update ($data)
delete ($ids)
method_getData ($params)
method_create ($params)
method_update ($params)
method_delete ($params)
Public Attributes
$table
$key_id = "id"
$key_namedId = "namedId"
$key_descriptiveName = "name"
$table_link_user_roles = "link_user_roles"
$table_link_roles_permissions = "link_roles_permissions"
$icon
$foreignKey = "Needs to be overridden!"
Detailed Description
common base class for permissions, roles and users providing a backend to the qcl.auth client package
Definition at line 13 of file common.php.
Constructor & Destructor Documentation
qcl_auth_common::__construct ()
constructor
Reimplemented from qcl_jsonrpc_object.
Reimplemented in qcl_auth_permission, qcl_auth_role, qcl_auth_user, class_authConfig, class_role, and class_user.
Definition at line 36 of file common.php.
References qcl_db::getSubclass().
Member Function Documentation
qcl_auth_common::getIdFromRef ($ ref)
gets the record id from a reference which can be the id itself or an identifiying (dot-separated) name
Parameters:
mixed $ref numeric id or string name
Returns:
integer id
Definition at line 52 of file common.php.
References qcl_jsonrpc_object::$result, and qcl_jsonrpc_object::raiseError().
Referenced by qcl_auth_user::addToRole(), qcl_auth_permission::addToRole(), qcl_auth_user::getPermissions(), qcl_auth_role::getPermissions(), qcl_auth_user::getRoles(), qcl_auth_user::removeFromRole(), and qcl_auth_permission::removeFromRole().
qcl_auth_common::getAll ($ orderBy = null)
gets all database records
Parameters:
string (optional, default null) order by field
Returns:
Array Array of db record sets
Definition at line 77 of file common.php.
Referenced by getAllNames(), and class_authConfig::method_getUsersAndRoles().
qcl_auth_common::getById ($ id)
get record by id
Returns:
Array Db record set
Definition at line 94 of file common.php.
Referenced by getByRef(), method_getData(), and class_authConfig::method_getUserNode().
qcl_auth_common::getByName ($ name)
get record by its (dot-separated) identifying name
Returns:
Array Db record set
Definition at line 107 of file common.php.
Referenced by qcl_auth_user::authenticate(), getByRef(), qcl_auth_user::getSecurity(), and qcl_auth_user::hasPermission().
qcl_auth_common::getByRef ($ ref)
get record by reference
Parameters:
mixed $ref numeric id or string name
Definition at line 120 of file common.php.
References getById(), getByName(), and qcl_jsonrpc_object::raiseError().
Referenced by getDescriptiveName().
qcl_auth_common::getDescriptiveName ($ ref)
get descriptive name of role
Parameters:
mixed $ref numeric id or string name
Returns:
string
Definition at line 141 of file common.php.
References getByRef().
qcl_auth_common::getAllNames ()
gets all identifying names
Definition at line 150 of file common.php.
References qcl_jsonrpc_object::$result, and getAll().
qcl_auth_common::insert ($ row)
inserts a record into a table and returns last_insert_id()
Parameters:
array $data associative array with the column names as keys and the column data as values
Returns:
int the id of the inserted row (only if auto_incremnt-key)
Definition at line 166 of file common.php.
Referenced by method_create().
qcl_auth_common::update ($ data)
updates a record in a table identified by id
Parameters:
array $data associative array with the column names as keys and the column data as values
Returns:
boolean success
Definition at line 176 of file common.php.
Referenced by method_update().
qcl_auth_common::delete ($ ids)
deletes a record in a table identified by id
Todo:
: check for linked entries, either delete them or refuse to delete
Parameters:
mixed $ids (array of) record id(s)
Definition at line 186 of file common.php.
qcl_auth_common::method_getData ($ params)
get item data
Parameters:
int $param[0] id
Returns:
array
Definition at line 201 of file common.php.
References qcl_jsonrpc_object::$result, getById(), and qcl_jsonrpc_object::getResult().
qcl_auth_common::method_create ($ params)
create a new item
Parameters:
$param[1] named id of new item
$param[2] id of parent of new item
Returns:
array
Definition at line 230 of file common.php.
References qcl_jsonrpc_object::addMessage(), qcl_jsonrpc_object::getResult(), and insert().
qcl_auth_common::method_update ($ params)
update item data
Parameters:
object $param[1] map of data properties to update and including the id
int $param[2] (optional) if the id is not contained in the data, provide it here
Returns:
array
Definition at line 261 of file common.php.
References qcl_jsonrpc_object::addMessage(), qcl_jsonrpc_object::getResult(), qcl_jsonrpc_object::raiseError(), and update().
qcl_auth_common::method_delete ($ params)
delete an item
Parameters:
int $param[1] item id
int $param[2] parent id
Returns:
array
Definition at line 293 of file common.php.
References qcl_jsonrpc_object::addMessage(), and qcl_jsonrpc_object::getResult().
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/auth/common.php