qcl sample application: qcl_jsonrpc_db Class Reference
qcl_jsonrpc_db Class Reference
Public Member Functions
__construct ()
& connect ()
& query ($sql)
& execute ($sql)
& getRow ($sql)
& getAllRows ($sql)
insert ($table, $data)
update ($table, $data, $idColumn)
delete ($table, $data, $idColumn)
escape ($string)
getLastInsertId ()
disconnect ()
__destruct ()
Public Attributes
$db
$dsn
Detailed Description
abstract class for rpc objects which do database queries implemented by subclasses with specific database adapters
Definition at line 9 of file db.php.
Constructor & Destructor Documentation
qcl_jsonrpc_db::__construct ()
constructor, reads database configuration
Reimplemented from qcl_jsonrpc_object.
Reimplemented in qcl_jsonrpc_config_db, and qcl_jsonrpc_db_pear.
Definition at line 25 of file db.php.
References connect().
qcl_jsonrpc_db::__destruct ()
destructor, disconnects from database
Definition at line 99 of file db.php.
References disconnect().
Member Function Documentation
& qcl_jsonrpc_db::connect ()
makes connection
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 37 of file db.php.
Referenced by __construct().
& qcl_jsonrpc_db::query ($ sql)
queries database
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 42 of file db.php.
& qcl_jsonrpc_db::execute ($ sql)
executes a query, alias of $this->query
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 47 of file db.php.
& qcl_jsonrpc_db::getRow ($ sql)
get first row of result set
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 52 of file db.php.
& qcl_jsonrpc_db::getAllRows ($ sql)
gets whole result set mapped to array
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 57 of file db.php.
qcl_jsonrpc_db::insert ($ table, $ data)
inserts a record into a table and returns last_insert_id()
Parameters:
string $table table name
array $data associative array with the column names as keys and the column data as values
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 64 of file db.php.
qcl_jsonrpc_db::update ($ table, $ data, $ idColumn)
updates a record in a table identified by id
Parameters:
string $table table name
array $data associative array with the column names as keys and the column data as values
string $idColumn name of column containing the record id
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 72 of file db.php.
qcl_jsonrpc_db::delete ($ table, $ data, $ idColumn)
deletes a record in a table identified by id
Parameters:
string $table table name
string $idColumn name of column containing the record id
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 79 of file db.php.
qcl_jsonrpc_db::escape ($ string)
escapes strings for use in sql queries
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 84 of file db.php.
qcl_jsonrpc_db::getLastInsertId ()
gets last inserted primary key
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 89 of file db.php.
qcl_jsonrpc_db::disconnect ()
disconnects from database
Reimplemented in qcl_jsonrpc_db_pear.
Definition at line 94 of file db.php.
Referenced by __destruct().
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/jsonrpc/db.php