qcl sample application: qcl_config_db Class Reference
qcl_config_db Class Reference
Public Member Functions
__construct ()
create ($name, $type, $permissionRead=null, $permissionWrite=null, $allowUserVariants=false)
update ($id, $key, $value)
delete ($ref)
get ($name)
getRow ($name, $userRef=null)
getRowById ($id)
getAll ($mask=null)
set ($name, $value, $defaultValue=false)
reset ($name)
getPermissionRead ($name)
getPermissionWrite ($name)
hasReadAccess ($name)
hasWriteAccess ($name)
Public Attributes
$table = "config"
$key_id = "id"
$key_name = "namedId"
$key_type = "type"
$key_value = "value"
$key_permissionRead = "permissionRead"
$key_permissionWrite = "permissionWrite"
$key_userId = "userId"
Detailed Description
configuration management class, using a database backend
### NOT YET FUNCTIONAL ###
Class cannot be used directly, you need to subclass it in your application service class folder
Definition at line 12 of file db.php.
Constructor & Destructor Documentation
qcl_config_db::__construct ()
constructor calls parent constructor
Parameters:
array $ini initial configuration
Reimplemented from qcl_config.
Definition at line 36 of file db.php.
References qcl_jsonrpc_object::getSingleton(), and qcl_db::getSubclass().
Member Function Documentation
qcl_config_db::create ($ name, $ type, $ permissionRead = null, $ permissionWrite = null, $ allowUserVariants = false)
creates a config property, overwriting any previous entry requires permission "qcl.config.permissions.manage"
Parameters:
string $name The name of the property (i.e., myapplication.config.locale)
string $type The type of the property (string|number|object|boolean)
string $permissionRead The permission name that is needed to access and read this property (optional)
string $permissionWrite The permission name that is needed to access and read this property (optional)
boolean $allowUserVariants If true, allow users to create their own variant of the configuration setting
Returns:
id of created config entry
Reimplemented from qcl_config.
Definition at line 61 of file db.php.
References qcl_jsonrpc_object::raiseError().
qcl_config_db::update ($ id, $ key, $ value)
updates a config property requires permission "qcl.config.permissions.manage"
Parameters:
mixed $id ID of property
string $key Key to update
mixed $value Value
Returns:
true if success
Reimplemented from qcl_config.
Definition at line 105 of file db.php.
qcl_config_db::delete ($ ref)
deletes a config property completely or only its user variant requires permission qcl.config.permissions.manage
Parameters:
mixed $ref Id or name of the property (i.e., myapplication.config.locale)
Returns:
true if success
Reimplemented from qcl_config.
Definition at line 121 of file db.php.
qcl_config_db::get ($ name)
gets config property value
Parameters:
string $name The name of the property (i.e., myapplication.config.locale)
Returns:
value of property or null if value does not exist.
Reimplemented from qcl_config.
Definition at line 147 of file db.php.
qcl_config_db::getRow ($ name, $ userRef = null)
gets the database record for the config entry and for the specific user
Parameters:
string $name
mixed $userRef
Definition at line 158 of file db.php.
Referenced by getPermissionRead(), getPermissionWrite(), and set().
qcl_config_db::getRowById ($ id)
gets config data by id
Parameters:
string $id The row id of the key
Returns:
array row data
Definition at line 235 of file db.php.
References qcl_jsonrpc_object::raiseError().
qcl_config_db::getAll ($ mask = null)
gets all config property value that are readable by the active user
Parameters:
string $mask return only a subset of entries that start with $mask
Returns:
array Array
Reimplemented from qcl_config.
Definition at line 263 of file db.php.
References qcl_jsonrpc_object::$result.
qcl_config_db::set ($ name, $ value, $ defaultValue = false)
sets config property
Parameters:
string $name The name of the property (i.e., myapplication.config.locale)
string $value The value of the property.
boolean $defaultValue If true, set the key's default value for keys that allow user variants. This is necessary so that the admin can change the defaults instead of editing her/his own variant.
Returns:
true if success or false if there was an error
Reimplemented from qcl_config.
Definition at line 308 of file db.php.
References getRow(), and qcl_jsonrpc_object::raiseError().
qcl_config_db::reset ($ name)
resets a property user variant to its original value raise an error if the active user does not have write permission for this property
Parameters:
string $name The name of the property (i.e., myapplication.config.locale)
Returns:
true if success or false if there was an error
Reimplemented from qcl_config.
Definition at line 382 of file db.php.
References qcl_jsonrpc_object::raiseError().
qcl_config_db::getPermissionRead ($ name)
gets required permission name for read access to config property
Parameters:
string $name name of configuration key
Reimplemented from qcl_config.
Definition at line 391 of file db.php.
References getRow().
Referenced by hasReadAccess().
qcl_config_db::getPermissionWrite ($ name)
gets required permission name for write access to config property
Parameters:
string $name name of configuration key
Reimplemented from qcl_config.
Definition at line 401 of file db.php.
References getRow().
Referenced by hasWriteAccess().
qcl_config_db::hasReadAccess ($ name)
checks if current user has the right to access the configuration property with read priviledges
Parameters:
string $name name of configuration key
Reimplemented from qcl_config.
Definition at line 412 of file db.php.
References getPermissionRead().
qcl_config_db::hasWriteAccess ($ name)
checks if current user has the right to access the configuration property with write priviledges
Parameters:
string $name name of configuration key
Reimplemented from qcl_config.
Definition at line 422 of file db.php.
References getPermissionWrite().
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/config/db.php