qcl sample application: qcl_config_manager Class Reference
qcl_config_manager Class Reference
Public Member Functions
__construct ()
method_updateClient ($params)
method_updateServer ($params)
method_create ($params)
method_update ($params)
method_delete ($params)
method_set ($params)
method_getAll ($params)
Detailed Description
Service class providing data to the config manager on the client
Definition at line 12 of file manager.php.
Constructor & Destructor Documentation
qcl_config_manager::__construct ()
constructor
Reimplemented from qcl_jsonrpc_object.
Reimplemented in class_configManager.
Definition at line 22 of file manager.php.
References qcl_config::getSubclass().
Member Function Documentation
qcl_config_manager::method_updateClient ($ params)
default update client method: retrieves all accessible config keys
Parameters:
string $params[0] retrieve only subset starting with $params[0]
Definition at line 36 of file manager.php.
References qcl_jsonrpc_object::$result, and qcl_jsonrpc_object::getResult().
qcl_config_manager::method_updateServer ($ params)
default update server method: updates selected config keys
Parameters:
object $params[1] map of configuration key values to update
Definition at line 54 of file manager.php.
References qcl_jsonrpc_object::getResult().
qcl_config_manager::method_create ($ params)
creates a config property, overwriting any previous entry requires permission "qcl.config.permissions.manage"
Parameters:
string $params[1]->name The name of the property (i.e., myapplication.config.locale)
string $params[1]->type The type of the property (string|number|object|boolean)
string $params[1]->permissionRead The permission name that is needed to access and read this property (optional)
string $params[1]->permissionWrite The permission name that is needed to access and read this property (optional)
boolean $params[1]->allowUserVariants If true, allow users to create their own variant of the configuration setting
Returns:
true if success
Definition at line 79 of file manager.php.
References qcl_jsonrpc_object::addMessage(), and qcl_jsonrpc_object::getResult().
qcl_config_manager::method_update ($ params)
updates a config property requires permission "qcl.config.permissions.manage"
Parameters:
mixed $params[1] ID of property
string $params[2] Key to update
mixed $params[3] Value
Returns:
true if success
Definition at line 101 of file manager.php.
References qcl_jsonrpc_object::addMessage(), and qcl_jsonrpc_object::getResult().
qcl_config_manager::method_delete ($ params)
deletes a config property completely or only its user variant requires permission qcl.config.permissions.manage
Parameters:
mixed $params[1] Id or name of the property (i.e., myapplication.config.locale)
Returns:
true if success
Definition at line 128 of file manager.php.
References qcl_jsonrpc_object::getResult().
qcl_config_manager::method_set ($ params)
sets config property
Parameters:
string $params[0] The name of the property (i.e., myapplication.config.locale)
string $params[1] The value of the property.
boolean $params[3] If true, set the key's default value for keys that allow user variants. This is necessary so that the admin can change the defaults instead of editing her/his own variant.
Returns:
true if success
Definition at line 143 of file manager.php.
References qcl_jsonrpc_object::addMessage(), and qcl_jsonrpc_object::getResult().
qcl_config_manager::method_getAll ($ params)
gets all config property value that are readable by the active user
Parameters:
string $param[0] return only a subset of entries that start with $mask
Returns:
array tabledatamodel
Definition at line 157 of file manager.php.
References qcl_jsonrpc_object::getResult().
The documentation for this class was generated from the following file:
F:/xampp/htdocs/qooxdoo-contrib/qcl/trunk/sample_app/backend/php/services/qcl/config/manager.php